### ISSUE TITLE
Imports should use the global namespace

### ISSUE THREAD

**Issue by jjneely** [ronnycorral/siteutils#2]
https://github.com/ronnycorral/siteutils/blob/5aef284918a8106a2fb3ba59ed000ea5611c76ec/parsehttplogs/parsehttplogs.go#L29

This should be a global import path.

**Comment by ronnycorral** [comment]
I'm going to have to ponder this a bit. I asked about this earlier and I either misunderstood what you said or I'm implementing it incorrectly. Or both...

**Comment by ronnycorral** [comment]
The guy giving Go class today made a comment about changing GOPATH which confirmed to me an idea I had for resolving this. I shifted things around and was able to resolve the path issue.
